# Generated by Django 4.1.1 on 2022-10-06 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gadugadu_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='descrption',
            new_name='description',
        ),
    ]
